spring:
  application:
    name: belajar-springboot-restful-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ryzen5600
    url: JDBC:mysql://localhost:3306/belajar_springboot_restful_api?useSSL=false&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    Hikari:
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true